// 花云机场节点 -> https://affman.vercel.app/flower
const flowerList = [
  { name: 'Traffic: 1.24 GB | 20 GB' },
  { name: 'Expire: 2023-04-10' },
  { name: '香港实验性 IEPL 中继 1' },
  { name: '日本实验性 IEPL 中继 1' },
  { name: '新加坡实验性 IEPL 中继 1' },
  { name: '美国实验性 IEPL 中继 1' },
  { name: '香港高级 IEPL 中继 1' },
  { name: '香港高级 IEPL 中继 2' },
  { name: '香港高级 IEPL 中继 3' },
  { name: '日本高级 IEPL 中继 1' },
  { name: '日本高级 IEPL 中继 2' },
  { name: '日本高级 IEPL 中继 3' },
  { name: '新加坡高级 IEPL 中继 1' },
  { name: '新加坡高级 IEPL 中继 2' },
  { name: '新加坡高级 IEPL 中继 3' },
  { name: '台湾高级 IEPL 中继 1' },
  { name: '台湾高级 IEPL 中继 2' },
  { name: '台湾高级 IEPL 中继 3' },
  { name: '美国高级 IEPL 中继 1' },
  { name: '美国高级 IEPL 中继 2' },
  { name: '美国高级 IEPL 中继 3' },
  { name: '香港标准 IEPL 中继 1' },
  { name: '香港标准 IEPL 中继 2' },
  { name: '香港标准 IEPL 中继 3' },
  { name: '香港标准 IEPL 中继 4' },
  { name: '香港标准 IEPL 中继 5' },
  { name: '香港标准 IEPL 中继 6' },
  { name: '香港标准 IEPL 中继 7' },
  { name: '香港标准 IEPL 中继 8' },
  { name: '日本标准 IEPL 中继 1' },
  { name: '日本标准 IEPL 中继 2' },
  { name: '日本标准 IEPL 中继 3' },
  { name: '日本标准 IEPL 中继 4' },
  { name: '日本标准 IEPL 中继 5' },
  { name: '日本标准 IEPL 中继 6' },
  { name: '日本标准 IEPL 中继 7' },
  { name: '日本标准 IEPL 中继 8' },
  { name: '韩国标准 IEPL 中继 1' },
  { name: '韩国标准 IEPL 中继 2' },
  { name: '印尼标准 IEPL 中继 1' },
  { name: '泰国标准 IEPL 中继 1' },
  { name: '越南标准 IEPL 中继 1' },
  { name: '印度标准 IEPL 中继 1' },
  { name: '以色列标准 IEPL 中继 1' },
  { name: '阿联酋标准 IEPL 中继 1' },
  { name: '菲律宾标准 IEPL 中继 1' },
  { name: '马来西亚标准 IEPL 中继 1' },
  { name: '南非标准 IEPL 中继 1' },
  { name: '新加坡标准 IEPL 中继 1' },
  { name: '新加坡标准 IEPL 中继 2' },
  { name: '新加坡标准 IEPL 中继 3' },
  { name: '新加坡标准 IEPL 中继 4' },
  { name: '新加坡标准 IEPL 中继 5' },
  { name: '新加坡标准 IEPL 中继 6' },
  { name: '新加坡标准 IEPL 中继 7' },
  { name: '新加坡标准 IEPL 中继 8' },
  { name: '台湾标准 IEPL 中继 1' },
  { name: '台湾标准 IEPL 中继 2' },
  { name: '台湾标准 IEPL 中继 3' },
  { name: '美国标准 IEPL 中继 1' },
  { name: '美国标准 IEPL 中继 2' },
  { name: '美国标准 IEPL 中继 3' },
  { name: '美国标准 IEPL 中继 4' },
  { name: '美国标准 IEPL 中继 5' },
  { name: '美国标准 IEPL 中继 6' },
  { name: '美国标准 IEPL 中继 7' },
  { name: '美国标准 IEPL 中继 8' },
  { name: '俄罗斯标准 IEPL 中继 1' },
  { name: '乌克兰标准 IEPL 中继 1' },
  { name: '意大利标准 IEPL 中继 1' },
  { name: '匈牙利标准 IEPL 中继 1' },
  { name: '土耳其标准 IEPL 中继 1' },
  { name: '土耳其标准 IEPL 中继 2' },
  { name: '加拿大标准 IEPL 中继 1' },
  { name: '阿根廷标准 IEPL 中继 1' },
  { name: '德国标准 IEPL 中继 1' },
  { name: '德国标准 IEPL 中继 2' },
  { name: '英国标准 IEPL 中继 1' },
  { name: '英国标准 IEPL 中继 2' },
  { name: '荷兰标准 IEPL 中继 1' },
  { name: '荷兰标准 IEPL 中继 2' },
  { name: '法国标准 IEPL 中继 1' },
  { name: '法国标准 IEPL 中继 2' },
  { name: '巴西标准 IEPL 中继 1' },
  { name: '澳洲标准 IEPL 中继 1' }
]

// Texon机场节点 -> https://affman.vercel.app/texon
const texonList = [
  { name: '香港雞蛋仔 1' },
  { name: '香港燒鴨飯 2' },
  { name: '台灣豬血湯 1' },
  { name: '台灣牛舌餅 2' },
  { name: '新加坡叻沙 1' },
  { name: '新加坡辣蟹 2' },
  { name: '日本鯛魚燒 1' },
  { name: '日本烏賊燒 2' },
  { name: '美國甜甜圈 1' },
  { name: '美國法士達 2' }
]

// pinkSeason -> https://affman.vercel.app/ps
const pinkSeasonList = [
  { name: '香港 - 海洋公园' },
  { name: '台湾 - 阿里山' },
  { name: '日本 - 秋叶原' },
  { name: '新加坡 - 鱼尾狮' },
  { name: '美国 - 金门大桥' },
  { name: '韩国 - 首尔塔' }
]

// 魔戒 -> https://affman.vercel.app/mojie
const mojieList = [
  { name: '日本-智能' },
  { name: '日本-优化2' },
  { name: '日本-优化' },
  { name: '日本' },
  { name: '日本-优化3' },
  { name: '新加坡-智能' },
  { name: '新加坡' },
  { name: '新加坡-优化2' },
  { name: '新加坡-优化' },
  { name: '马来西亚-优化' },
  { name: '新加坡-优化3' },
  { name: '马来西亚-优化3' },
  { name: '马来西亚-优化2' },
  { name: '香港-优化3' },
  { name: '香港-优化' },
  { name: '香港-隧道2' },
  { name: '香港-隧道' },
  { name: '香港Az-优化' },
  { name: '香港-隧道3' },
  { name: '香港Az-优化3' },
  { name: '香港Az-优化2' },
  { name: '香港环电-隧道2' },
  { name: '香港环电-隧道1' },
  { name: '香港HGC-优化' },
  { name: '香港环电-隧道3' },
  { name: '香港HGC-优化3' },
  { name: '香港HGC-优化2' },
  { name: '香港HKT2-优化' },
  { name: '香港HKT2' },
  { name: '香港HKT2-优化3' },
  { name: '香港HKT2-优化2' },
  { name: '韩国-智能' },
  { name: '香港环电' },
  { name: '韩国-优化2' },
  { name: '韩国-优化' },
  { name: '印度-智能' },
  { name: '韩国-优化3' },
  { name: '台湾-智能' },
  { name: '印度-优化' },
  { name: '台湾-优化2' },
  { name: '台湾-优化' },
  { name: '柬埔寨-优化' },
  { name: '台湾-优化3' },
  { name: '德国-优化' },
  { name: '柬埔寨-优化2' },
  { name: '德国-优化3' },
  { name: '德国-优化2' },
  { name: '美国-优化2' },
  { name: '美国-优化' },
  { name: '英国-优化' },
  { name: '美国-优化3' },
  { name: '英国-优化3' },
  { name: '英国-优化2' },
  { name: '法国-优化2' },
  { name: '法国-优化' },
  { name: '俄罗斯-优化' },
  { name: '法国-优化3' },
  { name: '阿根廷-优化3' },
  { name: '阿根廷-优化1' },
  { name: '巴西-优化2' },
  { name: '巴西-优化1' },
  { name: '墨西哥-优化1' },
  { name: '巴西-优化3' },
  { name: '墨西哥-优化3' },
  { name: '墨西哥-优化2' }
]

// 果粒橙
const glcList = [
  { name: '香港HKT' },
  { name: '官网:guolicheng.cc' },
  { name: 'TG: https://t.me/Goguolichengo' },
  { name: '香港HGC' },
  { name: '新加坡DO-1号' },
  { name: '新加坡DO-2号' },
  { name: 'linode日本-1号' },
  { name: 'linode日本-2号' },
  { name: '法国Do1号' },
  { name: '法国Do2号' },
  { name: '德国Linode-1号' },
  { name: '德国-1号' },
  { name: '香港1号' },
  { name: '香港2号 2x' },
  { name: '台湾SCloud | 直连' },
  { name: '台湾Hinet' },
  { name: '香港M247-1号(移动网用户专享)' },
  { name: '香港M247-2号(移动网用户专享)' },
  { name: '香港M247-3号(移动网用户专享)' },
  { name: '香港M247-4号(移动网用户专享)' },
  { name: '韩国亚马逊-1号' },
  { name: '韩国亚马逊-2号' },
  { name: '韩国亚马逊-3号' },
  { name: 'Oracle日本东京-1号' },
  { name: 'Oracle日本东京-广移负载均衡双线聚合 | 解流媒体' }
]
// ytoo
const ytooList = [
  { name: 'Traffic:79.69 GB 600 GB' },
  { name: 'Expire:-0001-11-30' },
  { name: '实验专线香港[0.2]' },
  { name: '实验专线狮城[0.2]' },
  { name: '实验专线日本[0.2]' },
  { name: '实验专线美国[0.2]' },
  { name: '高级专线香港01' },
  { name: '高级专线香港02' },
  { name: '高级专线香港03' },
  { name: '高级专线香港04' },
  { name: '高级专线香港05' },
  { name: '高级专线狮城01' },
  { name: '高级专线狮城02' },
  { name: '高级专线狮城03' },
  { name: '高级专线狮城04' },
  { name: '高级专线狮城05' },
  { name: '高级专线美国01' },
  { name: '高级专线美国02' },
  { name: '高级专线美国03' },
  { name: '高级专线美国04' },
  { name: '高级专线美国05' },
  { name: '高级专线美国06' },
  { name: '高级专线美国07' },
  { name: '高级专线美国08' },
  { name: '高级专线韩国01' },
  { name: '高级专线韩国02' },
  { name: '高级专线台湾01' },
  { name: '高级专线台湾02' },
  { name: '高级专线日本01' },
  { name: '高级专线日本02' },
  { name: '高级专线日本03' },
  { name: '高级专线日本04' },
  { name: '标准专线香港01' },
  { name: '标准专线香港02' },
  { name: '标准专线香港03' },
  { name: '标准专线狮城01' },
  { name: '标准专线狮城02' },
  { name: '标准专线狮城03' },
  { name: '标准专线美国01' },
  { name: '标准专线美国02' },
  { name: '标准专线韩国01' },
  { name: '标准专线日本01' },
  { name: '标准专线日本02' },
  { name: '标准专线日本03' },
  { name: '标准专线日本04' },
  { name: '标准专线台湾01' },
  { name: '特殊专线伦敦01' },
  { name: '特殊专线伦敦02' },
  { name: '特殊专线德国01' },
  { name: '特殊专线德国02' },
  { name: '特殊专线加拿大01' },
  { name: '特殊专线加拿大02' },
  { name: '特殊专线泰国' },
  { name: '特殊专线越南' },
  { name: '特殊专线印度' },
  { name: '特殊专线悉尼' },
  { name: '特殊专线迪拜' },
  { name: '特殊专线法国' },
  { name: '特殊专线巴西' },
  { name: '特殊专线菲律宾' },
  { name: '特殊专线意大利' },
  { name: '特殊专线西班牙' },
  { name: '特殊专线匈牙利' },
  { name: '特殊专线以色列' },
  { name: '购物专线阿根廷[3.0]' },
  { name: '购物专线土耳其[3.0]' },
  { name: '购物专线俄罗斯[3.0]' }
]

// prpr https://affman.vercel.app/prpr
const prprList = [
  { name: '懒人节点01' },
  { name: '香港01' },
  { name: '香港02' },
  { name: '香港03' },
  { name: '香港04' },
  { name: '香港05' },
  { name: '香港06A' },
  { name: '香港07A' },
  { name: '台湾01' },
  { name: '台湾02' },
  { name: '台湾03A' },
  { name: '新加坡01A' },
  { name: '新加坡02' },
  { name: '新加坡03' },
  { name: '新加坡04' },
  { name: '日本01' },
  { name: '日本02' },
  { name: '日本03' },
  { name: '日本04' },
  { name: '韩国01' },
  { name: '韩国02' },
  { name: '美国01' },
  { name: '美国02' },
  { name: '美国03' },
  { name: '俄罗斯01' },
  { name: '巴西01' },
  { name: '阿根廷01' },
  { name: '土耳其01' },
  { name: '菲律宾01' },
  { name: '印度01' },
  { name: '巴基斯坦01' },
  { name: '英国01' },
  { name: '荷兰01' },
  { name: '南非01' },
  { name: '卢森堡01' },
  { name: '马来西亚01' },
  { name: '泰国01' },
  { name: '阿联酉01' },
  { name: '法国01' },
  { name: '德国01' },
  { name: '加拿大01' },
  { name: '乌克兰01' },
  { name: '意大利01' },
  { name: '澳门01' },
  { name: '澳洲01' }
]
const testList = [{ name: 'Hong Kong LB（Load Balanced）' }]
